Traceback (most recent call last):
  File "/home/xdhpc/dits/Latte/train.py", line 293, in <module>
    main(OmegaConf.load(args.config))
  File "/home/xdhpc/dits/Latte/train.py", line 84, in main
    wandb.config.update(args)  # 记录超参数
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 187, in update
    sanitized = self._update(d, allow_val_change)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 180, in _update
    sanitized = self._sanitize_dict(
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 267, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 285, in _sanitize
    val = json_friendly_val(val)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/util.py", line 646, in json_friendly_val
    converted = asdict(val)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
Traceback (most recent call last):
  File "/home/xdhpc/dits/Latte/train.py", line 293, in <module>
    main(OmegaConf.load(args.config))
  File "/home/xdhpc/dits/Latte/train.py", line 84, in main
    wandb.config.update(args)  # 记录超参数
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 187, in update
    sanitized = self._update(d, allow_val_change)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 180, in _update
    sanitized = self._sanitize_dict(
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 267, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 285, in _sanitize
    val = json_friendly_val(val)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/site-packages/wandb/util.py", line 646, in json_friendly_val
    converted = asdict(val)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/xdhpc/miniconda3/envs/latte/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
